# Generated by Django 5.0.6 on 2026-05-17 16:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_home', models.CharField(max_length=200)),
                ('team_away', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('programado', 'Programado'), ('en_vivo', 'En Vivo'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido'), ('anulado', 'Anulado')], default='programado', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1X2', 'Ganador de Partido'), ('DOUBLE_CHANCE', 'Doble Oportunidad'), ('DRAW_NO_BET', 'Draw No Bet'), ('OU_05', 'Over/Under 0.5 Goles'), ('OU_15', 'Over/Under 1.5 Goles'), ('OU_25', 'Over/Under 2.5 Goles'), ('OU_35', 'Over/Under 3.5 Goles'), ('OU_45', 'Over/Under 4.5 Goles'), ('BTTS', 'Ambos Equipos Anotan'), ('BTTS_OU25', 'BTTS + Over/Under 2.5'), ('HOME_OU_15', 'Total Goles Local O/U 1.5'), ('AWAY_OU_05', 'Total Goles Visitante O/U 0.5'), ('HT_FT', 'Resultado Descanso/Final'), ('HT_1X2', 'Primer Tiempo 1X2'), ('HT_OU_15', 'Primer Tiempo O/U 1.5'), ('HC_0', 'Handicap Asiatico 0'), ('HC_M05', 'Handicap Asiatico -0.5'), ('HC_M1', 'Handicap Asiatico -1'), ('HC_M15', 'Handicap Asiatico -1.5'), ('HC_M2', 'Handicap Asiatico -2'), ('HC_EURO', 'Handicap Europeo -1'), ('CORRECT_SCORE', 'Marcador Exacto'), ('ODD_EVEN', 'Par/Impar Goles'), ('BTTS_1H', 'Ambos Marcan 1er Tiempo'), ('CLEAN_HOME', 'Clean Sheet Local'), ('CLEAN_AWAY', 'Clean Sheet Visitante'), ('FIRST_SCORE', 'Primer Equipo en Anotar'), ('MULTI_HOME', 'Multi-Goles Local'), ('MULTI_AWAY', 'Multi-Goles Visitante'), ('CORNERS_OU', 'Córneres O/U 9.5'), ('TENNIS_WINNER', 'Ganador del Partido'), ('TENNIS_HC', 'Hándicap Juegos'), ('TENNIS_TOTAL', 'Total Juegos O/U'), ('TENNIS_SET', 'Set Betting'), ('TENNIS_SET1', 'Primer Set Ganador'), ('TENNIS_SET1_TOT', 'Total Juegos Set 1 O/U'), ('TENNIS_BOTH', 'Ambos Ganaran un Set'), ('BASKET_ML', 'Moneyline'), ('BASKET_SPREAD', 'Spread'), ('BASKET_TOTAL', 'Total Puntos O/U'), ('BASKET_HT_SPR', 'Handicap Mitad'), ('BASKET_HT_ML', 'Mitad 1X2'), ('BASKET_HOME_TOT', 'Total Puntos Local O/U')], max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('is_live', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('odds', models.DecimalField(decimal_places=4, max_digits=18)),
                ('is_winner', models.BooleanField(blank=True, default=None, null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='events.market')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.sport'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='events_even_status_5709b6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['sport', 'status'], name='events_even_sport_i_0fe643_idx'),
        ),
    ]
