# Generated by Django 5.0.6 on 2026-05-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
