# Generated by Django 5.0.6 on 2026-05-17 16:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.DecimalField(decimal_places=4, max_digits=18)),
                ('total_odds', models.DecimalField(decimal_places=4, max_digits=18)),
                ('status', models.CharField(choices=[('accepted', 'Aceptada'), ('won', 'Ganada'), ('lost', 'Perdida'), ('cashed_out', 'Cobrada Anticipadamente'), ('cancelled', 'Cancelada')], default='accepted', max_length=20)),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('payout', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='BetSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odds_at_time', models.DecimalField(decimal_places=4, max_digits=18)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='betting.bet')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_selections', to='events.selection')),
            ],
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', 'status'], name='betting_bet_user_id_3cd6b5_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['status'], name='betting_bet_status_69d9a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='betselection',
            unique_together={('bet', 'selection')},
        ),
    ]
