# Generated by Django 5.0.6 on 2026-05-17 23:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('bienvenida', 'Bono de Bienvenida'), ('recarga', 'Bono de Recarga')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('monto_max', models.DecimalField(decimal_places=4, default=100, max_digits=18)),
                ('rollover_requerido', models.PositiveIntegerField(default=5)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_bono', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('rollover_completado', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('fecha_otorgado', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonuses.bonus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bonuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_otorgado'],
            },
        ),
    ]
